title: Girolamo Macaluso
logo: /assets/img/1545212646359.jpg
description: Phd Student at MICC 
theme: jekyll-theme-minimal
social-network-links:
  email: "girolamomacaluso@gmail.com"
  github: ganjiro
  twitter: daattali
  linkedin: https://www.linkedin.com/in/girolamo-macaluso-b50571164/

