# _config.yml
title: "Girolamo Macaluso"
email: girolamo.macaluso@unifi.it
description: "PhD Student in Artificial Intelligence at University of Florence"
baseurl: ""          # no subpath, since this is user site
url: "https://ganjiro.github.io"
theme: jekyll-theme-cayman

# Navigation links
nav:
  - title: Girolamo Macaluso
    url: /index.html
  - title: Resume
    url: /resume.html
  - title: Publications
    url: /publications.html
  - title: Teaching
    url: /teaching.html
# below existing settings
